In [1]:
#BAG OF WORDS

In [1]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [2]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [3]:
df=pd.read_csv("nlp2.csv",index_col=0)

In [4]:
df.head()

Text
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...
3  9. Baidu Research: Çin'in önde gelen arama mot...
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...

In [5]:
import on_islem

In [6]:
df["Text_2"] = df["Text"].apply(on_islem.pre_processing)
df["Text_2"] = df["Text_2"].apply(on_islem.remove_space)
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [7]:
#boş liste kontrolü
df[df["Text_2"].str[0].isnull()]

Text Text_2
194  #hesaplamalısosyalbilimler #computationalsocia...     []
464  #investment #software #technology #tech #innov...     []
544  @barolar #ImageRecognition #SınırlıHafıza #Lim...     []

In [8]:
df_index=df[df["Text_2"].str[0].isnull()].index
df=df.drop(df_index)
df=df.reset_index()
del df["index"]
df[df["Text_2"].str[0].isnull()]

Empty DataFrame
Columns: [Text, Text_2]
Index: []

In [9]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [10]:
df["Text_2"]

0      [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...
1      [veri, analiz, edin, chatgptyi, kullanarak, do...
2      [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...
3      [baidu, research, çin, ön, gele, ara, motor, b...
4      [microsoft, ai, microsoft, yapay, zeka, teknol...
                             ...                        
850    [doğal, dil, işle, alan, yük, lisansdoktor, ya...
851                              [dogal, dil, isle, şey]
852    [bir, ver, madencilik, ve, doğal, dil, işle, u...
853    [doğal, dil, işleme, il, ilgil, deney, ola, ya...
854    [hafta, öğrencilik, hayat, kaldık, yer, deva, ...
Name: Text_2, Length: 855, dtype: object

In [11]:
df["Text_3"]=[' '.join(w for w in item) for item in df["Text_2"]]
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2  \
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                            [dogal, dil, isle, şey]   
852  [bir, ver, madencilik, ve, doğal, dil, işle, u...   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...  
1    veri analiz edin chatgptyi kullanarak doğal di...  
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...  
3    baidu research çin ön gele ara motor baidun ar...  
4    microsoft ai microsoft yapay zeka teknoloji od...  
..                                                 ...  
850  doğal dil işle alan yük lisansdoktor yapa danı...  
851                                 dogal dil isle şey  
852     bir ver madencilik ve doğal dil işle uygulamas  
853  doğal dil işleme il ilgil deney ola yazılımcı ...  
854  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[855 rows x 3 columns]

In [12]:
vectorizer=CountVectorizer()
X = vectorizer.fit_transform(df["Text_3"].tolist())
X

<855x4805 sparse matrix of type '<class 'numpy.int64'>'
	with 18493 stored elements in Compressed Sparse Row format>

In [13]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
X[0]

<1x4805 sparse matrix of type '<class 'numpy.int64'>'
	with 31 stored elements in Compressed Sparse Row format>

In [15]:
df["Text_4"]= X.toarray().tolist()
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  \
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [16]:
#TF IDF

In [17]:
pip install tfidf

Note: you may need to restart the kernel to use updated packages.


In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
vectorizer= TfidfVectorizer()
X= vectorizer.fit_transform(df["Text_3"].tolist())

In [20]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [21]:
set(X.toarray()[0])

{0.0,
 0.03449692151729479,
 0.03623641834137704,
 0.06378276361301552,
 0.11301306304943211,
 0.12111903764726162,
 0.1265743863419305,
 0.12724026669658212,
 0.14688385470190235,
 0.15076597843523,
 0.15216874147572845,
 0.1536338696370362,
 0.16413009076644136,
 0.1709738752001381,
 0.173612079364325,
 0.1869761916955363,
 0.19645818029341997,
 0.20238330568742485,
 0.20982229262463126,
 0.21862406700445963,
 0.2193042812225149,
 0.23266839355372623,
 0.31096306040817345}

In [22]:
df["Text_5"]=X.toarray().tolist()

In [23]:
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2  \
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                            [dogal, dil, isle, şey]   
852  [bir, ver, madencilik, ve, doğal, dil, işle, u...   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  \
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                 dogal dil isle şey   
852     bir ver madencilik ve doğal dil işle uygulamas   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4  \
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[855 rows x 5 columns]

In [24]:
len(X.toarray()[0])

4805

In [25]:
#WORD2VEC

In [48]:
from gensim.models import Word2Vec

In [49]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  \
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [50]:
model = Word2Vec(sentences=df["Text_2"].tolist(), vector_size=100, window=5, min_count=1)
model.save("../data/word2vec.model")

In [51]:
words=list(model.wv.index_to_key)
words[0:6]

['dil', 'doğal', 'işle', 've', 'bir', 'yapay']

In [52]:
len(words)

4816

In [53]:
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2  \
0    [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
851                            [dogal, dil, isle, şey]   
852  [bir, ver, madencilik, ve, doğal, dil, işle, u...   
853  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  \
0    yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
850  doğal dil işle alan yük lisansdoktor yapa danı...   
851                                 dogal dil isle şey   
852     bir ver madencilik ve doğal dil işle uygulamas   
853  doğal dil işleme il ilgil deney ola yazılımcı ...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4  \
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[855 rows x 5 columns]

In [54]:
#kelimelerimizi vektör haline getirdik
model.wv.key_to_index["yapay"] 

5

In [55]:
model.wv[5]

array([-0.26148352,  0.2714678 ,  0.05663489,  0.11964748,  0.01845079,
       -0.42302516,  0.18549596,  0.66230124, -0.20743783, -0.31520322,
       -0.05375095, -0.42571205, -0.15406723,  0.05010691,  0.00086089,
       -0.1912589 ,  0.18640317, -0.35084194, -0.04138278, -0.5469407 ,
        0.19970201,  0.17485505,  0.3533469 , -0.05889947, -0.02572454,
        0.07419808, -0.2849858 , -0.03671542, -0.23046803, -0.05694999,
        0.42529857, -0.06086779,  0.00479859, -0.29799727, -0.07653974,
        0.26644686,  0.1159202 , -0.04589028, -0.17771278, -0.37403288,
        0.10822412, -0.2637861 , -0.08950468, -0.03897683,  0.2963102 ,
       -0.09288011, -0.20947738, -0.05589915,  0.2480777 ,  0.20364498,
        0.24806327, -0.2690116 ,  0.00983717, -0.13626035, -0.16176836,
        0.12825245,  0.25596252, -0.0605338 , -0.27202424,  0.03823816,
       -0.04030829,  0.08362938,  0.08629494,  0.07879042, -0.3593514 ,
        0.3330344 , -0.06894853,  0.23162207, -0.26837307,  0.30

In [60]:
def word2vec(value):
    model = Word2Vec.load("../data/word2vec.model")
    bfr_list = []
    bfr_len = len(value)
    
    for k in value:
        bfr = model.wv.key_to_index[k]
        bfr = model.wv[bfr]
        bfr_list.append(bfr)
        
    bfr_list = sum(bfr_list)
    bfr_list = bfr_list/bfr_len
    return bfr_list.tolist()

In [57]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  \
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [61]:
df["Text_6"] = df["Text_2"].apply(word2vec)

In [63]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir, ne, işe, yarar, yapay, ze...   
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, ne, olduğunu, iç, ne, ö...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3  \
0  yapay zeka nedir ne işe yarar yapay zeka yz bi...   
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka ne olduğunu iç ne önemli ol...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  \
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  \
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Text_6  
0  [-0.13510777056217194, 0.14389698207378387, 0....  
1  [-0.10580062121152878, 0.11390060186386108, 0....  
2  [-0.1256001740694046, 0.13623929023742676, 0.0...  
3  [-0.11547128856182098, 0.1243741437792778, 0.0...  
4  [-0.1563141793012619, 0.166717067360878, 0.034...